name: DémoMémoire
on: push
jobs:
  Clean: 
    name: Clean application
    runs-on: windows-latest
    steps:
      - name: Cleanup
        uses: ./.github/workflows/workflow-2.yml
  Build:
    name: Build application
    runs-on: windows-latest
    needs: [Clean]
    steps:
      - name: Build
        uses: octo-org/another-repo/.github/workflows/workflow.yml@v1    
  Test:
    name: Test application
    runs-on: windows-latest
    needs: [Build]
    steps:
      - name: Test
        run: dotnet test
      
        
