name: Créer et publier une image Docker

on:
  workflow_call:
    inputs:
        verison:
            type: string
        nomImage:
            required: true
            type: string
    secrets:
      Nom_utilisateur:
        required: true
      Mot_de_passe:
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:     
      - uses: actions/checkout@v3
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
      - name: Connection 
        uses: docker/login-action@v1
        with:
          username: ${{secrets.Nom_utilisateur}}
          password: ${{secrets.Mot_de_passe}}
      - name: Construire et pousser l'image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.Nom_utilisateur}}/${{inputs.nomImage}}:${{inputs.version}}
